version: '3.8'

services:
  app:
    build: .
    container_name: nest-app
    ports:
      - "80:3000"   # Changed to port 80 for HTTP
      - "443:5000"   # For SSL if needed
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start:dev
    environment:
      NODE_ENV: production
      JWT_SECRET: "AKENZY"
      HOST: 0.0.0.0
      PORT: 3000
      HOST_SOCKET: 0.0.0.0
      PORT_SOCKET: 5000
      MONGODB_URI: mongodb://mongo:27017/2School
      SALT_OF_ROUNDS: 10
      SWAGGER_PATH: "/api/docs"
      SWAGGER_TITLE: "2School"
      SWAGGER_DESCRIPTION: "The 2 2School API Description"
      SWAGGER_VERSION: "beta"
      SWAGGER_SCHEME: "http"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:5
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: 2School
    restart: unless-stopped

volumes:
  mongodb_data: