# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7
  docker: circleci/docker@1.4.0
jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: lamhan3012/nest-docker
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      - checkout
      # Please add $SSH_KEY_FINGERPRINT, $DEPLOYED_USER@ and DEPLOYED_SERVER to project's environment
      - add_ssh_keys:
          fingerprints:
            - '24:48:41:d3:9c:fc:14:0e:fb:47:84:9a:c1:5c:18:37'
      - run: ssh -oStrictHostKeyChecking=no root@natha-lms.tk './files/NestJS_2School/deploy.sh'

workflows:
  sample:
    # jobs:
    #   - build-and-push:
    #     filters:
    #         branches:
    #           only:
    #             - dev
    #             - master
      - deploy:
        # requires:
        # - build-and-push
        filters:
          branches:
            only:
              - dev
              - master


      # - node/test:
      #     version: '16.10'
      #     # # If you are using yarn, change the line below from "npm" to "yarn"
      #     pkg-manager: yarn
      #
      # This is the node version to use for the `cimg/node` tag
      # Relevant tags can be found on the CircleCI Developer Hub
      # https://circleci.com/developer/images/image/cimg/node
      # - build-and-push:
      #     requires:
      #       - node/test
      # filters:
      #   branches:
      #     only:
      #       - master
      # uncomment the 3 following lines to enable deploying
      # - deploy:
      #     requires:
      #       - node/test